services:
  twitch-recorder:
    image: sparklingsausage/streamlink-recorder
    container_name: twitch-recorder
    restart: unless-stopped
    environment:
      STREAMERS: streamer1,streamer2,streamer3 # DO NOT LEAVE SPACES, otherwise the online check won't work
      OUTPUT_DIR: /recordings # change if needed (don't recommend to do so)
      STREAM_QUALITY: best # change if needed
      CHECK_INTERVAL: 60 # maybe change it to 30 seconds if you want to
      STREAMLINK_ARGS: --twitch-disable-ads # other parameters can be added
    volumes:
      - /path/to/your/liking/:/recordings # change if you want
